services:
  - type: web
    name: my-tasks-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: "0.0.0.0"
      - key: CORS_ORIGIN
        value: "*"
      - key: LOG_LEVEL
        value: info
      - key: JWT_ACCESS_EXPIRES
        value: "15m"
      - key: JWT_REFRESH_EXPIRES
        value: "7d"
      - key: BCRYPT_COST
        value: "11"
      - key: RATE_LIMIT_AUTH
        value: "10"
      - key: RATE_LIMIT_TASKS
        value: "120"

databases:
  - name: my-tasks-db
    plan: free